# Compare code to assure same outputs

Comparing two ways to run the code to convince ourselves the outputs are the same and can be used as tests for further code updates.

1. Using Chao's original code on a downloaded hdf5 file
2. Using SlideRule to obtain the data and run the computations

Note: A generalized read-in function, along with a copy of the original function used by Chao to read in data, is located in the icepyx readdev.py file, imported locally below.

In [1]:
# not sure if this is needed anymore; restart kernel after running
%pip install --upgrade sliderule
%pip install icepyx

Requirement already satisfied: sliderule in /srv/conda/envs/notebook/lib/python3.12/site-packages (4.20.0)
Collecting sliderule
  Using cached sliderule-5.4.4-py3-none-any.whl.metadata (865 bytes)
Requirement already satisfied: requests in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sliderule) (2.32.5)
Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sliderule) (1.26.4)
Requirement already satisfied: geopandas in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sliderule) (1.1.2)
Requirement already satisfied: shapely in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sliderule) (2.0.7)
Requirement already satisfied: pyarrow in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sliderule) (18.1.0)
Requirement already satisfied: packaging in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geopandas->sliderule) (25.0)
Requirement already satisfied: pandas>=2.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from geopandas->sliderule) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas>=2.0.0->geopandas->sliderule) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas>=2.0.0->geopandas->sliderule) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas>=2.0.0->geopandas->sliderule) (2025.3)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas->sliderule) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->sliderule) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->sliderule) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->sliderule) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->sliderule) (2025.10.5)
Using cached sliderule-5.4.4-py3-none-any.whl (169 kB)
Installing collected packages: sliderule
  Attempting uninstall: sliderule
    Found existing installation: sliderule 4.20.0
    Uninstalling sliderule-4.20.0:
      Successfully uninstalled sliderule-4.20.0
Successfully installed sliderule-5.4.4
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: icepyx in /srv/conda/envs/notebook/lib/python3.12/site-packages (2.0.1)
Requirement already satisfied: backoff in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (2.2.1)
Requirement already satisfied: dask<2025.1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask[dataframe]<2025.1.0->icepyx) (2024.12.1)
Requirement already satisfied: datashader in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (0.18.2)
Requirement already satisfied: deprecated in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.3.1)
Requirement already satisfied: earthaccess>=0.15.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (0.16.0)
Requirement already satisfied: fiona in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.10.1)
Requirement already satisfied: geopandas in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.1.2)
Requirement already satisfied: h5netcdf in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.8.1)
Requirement already satisfied: h5py in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (3.13.0)
Requirement already satisfied: harmony-py>=1.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.3.3)
Requirement already satisfied: holoviews in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.22.1)
Requirement already satisfied: hvplot in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (0.12.2)
Requirement already satisfied: matplotlib in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (3.10.8)
Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (1.26.4)
Requirement already satisfied: requests in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (2.32.5)
Requirement already satisfied: s3fs in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (2026.2.0)
Requirement already satisfied: shapely in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (2.0.7)
Requirement already satisfied: xarray in /srv/conda/envs/notebook/lib/python3.12/site-packages (from icepyx) (2026.2.0)
Requirement already satisfied: click>=8.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (2026.2.0)
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (25.0)
Requirement already satisfied: partd>=1.4.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (1.1.0)
Requirement already satisfied: pandas>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask[dataframe]<2025.1.0->icepyx) (2.3.3)
Requirement already satisfied: dask-expr<1.2,>=1.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask[dataframe]<2025.1.0->icepyx) (1.1.21)
Requirement already satisfied: pyarrow>=14.0.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask-expr<1.2,>=1.1->dask[dataframe]<2025.1.0->icepyx) (18.1.0)
Requirement already satisfied: importlib-resources>=6.3.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (6.5.2)
Requirement already satisfied: multimethod>=1.8 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (2.0.2)
Requirement already satisfied: pqdm>=0.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (0.2.0)
Requirement already satisfied: python-cmr>=0.10.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (0.13.0)
Requirement already satisfied: tenacity>=8.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (9.1.4)
Requirement already satisfied: tinynetrc>=1.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (1.3.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthaccess>=0.15.1->icepyx) (4.15.0)
Requirement already satisfied: python-dateutil~=2.9 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from harmony-py>=1.0.0->icepyx) (2.9.0)
Requirement already satisfied: python-dotenv~=1.1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from harmony-py>=1.0.0->icepyx) (1.1.1)
Requirement already satisfied: progressbar2~=4.2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from harmony-py>=1.0.0->icepyx) (4.2.0)
Requirement already satisfied: sphinxcontrib-napoleon~=0.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from harmony-py>=1.0.0->icepyx) (0.7)
Requirement already satisfied: curlify~=2.2.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from harmony-py>=1.0.0->icepyx) (2.2.1)
Requirement already satisfied: python-utils>=3.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from progressbar2~=4.2.0->harmony-py>=1.0.0->icepyx) (3.9.1)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from python-dateutil~=2.9->harmony-py>=1.0.0->icepyx) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->icepyx) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->icepyx) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->icepyx) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->icepyx) (2025.10.5)
Requirement already satisfied: pockets>=0.3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from sphinxcontrib-napoleon~=0.7->harmony-py>=1.0.0->icepyx) (0.9.1)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas>=2.0->dask[dataframe]<2025.1.0->icepyx) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas>=2.0->dask[dataframe]<2025.1.0->icepyx) (2025.3)
Requirement already satisfied: locket in /srv/conda/envs/notebook/lib/python3.12/site-packages (from partd>=1.4.0->dask<2025.1.0->dask[dataframe]<2025.1.0->icepyx) (1.0.0)
Requirement already satisfied: bounded-pool-executor in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pqdm>=0.1->earthaccess>=0.15.1->icepyx) (0.0.3)
Requirement already satisfied: tqdm in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pqdm>=0.1->earthaccess>=0.15.1->icepyx) (4.67.3)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from s3fs->icepyx) (3.1.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from s3fs->icepyx) (3.13.3)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->icepyx) (0.13.0)
Requirement already satisfied: botocore<1.42.50,>=1.41.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->icepyx) (1.42.49)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->icepyx) (1.0.1)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->icepyx) (6.7.0)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->icepyx) (2.1.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (1.7.0)
Requirement already satisfied: propcache>=0.2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->icepyx) (1.22.0)
Requirement already satisfied: colorcet in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (3.1.0)
Requirement already satisfied: multipledispatch in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (0.6.0)
Requirement already satisfied: numba in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (0.63.1)
Requirement already satisfied: param in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (2.3.2)
Requirement already satisfied: pyct in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (0.6.0)
Requirement already satisfied: scipy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from datashader->icepyx) (1.17.0)
Requirement already satisfied: click-plugins>=1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fiona->icepyx) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from fiona->icepyx) (0.7.2)
Requirement already satisfied: bokeh>=3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from holoviews->icepyx) (3.8.2)
Requirement already satisfied: narwhals>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from holoviews->icepyx) (2.16.0)
Requirement already satisfied: panel>=1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from holoviews->icepyx) (1.8.7)
Requirement already satisfied: pyviz-comms>=2.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from holoviews->icepyx) (3.0.6)
Requirement already satisfied: Jinja2>=2.9 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bokeh>=3.1->holoviews->icepyx) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bokeh>=3.1->holoviews->icepyx) (1.3.3)
Requirement already satisfied: pillow>=7.1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bokeh>=3.1->holoviews->icepyx) (11.3.0)
Requirement already satisfied: tornado>=6.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bokeh>=3.1->holoviews->icepyx) (6.5.4)
Requirement already satisfied: xyzservices>=2021.09.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bokeh>=3.1->holoviews->icepyx) (2025.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews->icepyx) (3.0.3)
Requirement already satisfied: bleach in /srv/conda/envs/notebook/lib/python3.12/site-packages (from panel>=1.0->holoviews->icepyx) (6.2.0)
Requirement already satisfied: linkify-it-py in /srv/conda/envs/notebook/lib/python3.12/site-packages (from panel>=1.0->holoviews->icepyx) (2.0.3)
Requirement already satisfied: markdown in /srv/conda/envs/notebook/lib/python3.12/site-packages (from panel>=1.0->holoviews->icepyx) (3.10.2)
Requirement already satisfied: markdown-it-py in /srv/conda/envs/notebook/lib/python3.12/site-packages (from panel>=1.0->holoviews->icepyx) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /srv/conda/envs/notebook/lib/python3.12/site-packages (from panel>=1.0->holoviews->icepyx) (0.5.0)
Requirement already satisfied: webencodings in /srv/conda/envs/notebook/lib/python3.12/site-packages (from bleach->panel>=1.0->holoviews->icepyx) (0.5.1)
Requirement already satisfied: uc-micro-py in /srv/conda/envs/notebook/lib/python3.12/site-packages (from linkify-it-py->panel>=1.0->holoviews->icepyx) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from markdown-it-py->panel>=1.0->holoviews->icepyx) (0.1.2)
Requirement already satisfied: cycler>=0.10 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->icepyx) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->icepyx) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->icepyx) (1.4.9)
Requirement already satisfied: pyparsing>=3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from matplotlib->icepyx) (3.3.2)
Requirement already satisfied: llvmlite<0.47,>=0.46.0dev0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from numba->datashader->icepyx) (0.46.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import glob

%load_ext autoreload
import icepyx as ipx
import aok as aok
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [6]:
from datetime import datetime, timedelta
import time

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
# import rasterio as rio
# from rasterio.session import AWSSession
from shapely.geometry import Polygon
import xarray as xr

import boto3
import earthaccess
import icepyx as ipx
from sliderule import sliderule, icesat2 #, io

In [7]:
# 2. Grab spatial inputs from test file

# TODO: add typing to these functions and the code that grabs the test cases, below.

import yaml
from pathlib import Path
from shapely.geometry import Point

def load_test_sites(path="./test_sites.yaml"):
    with Path(path).open("r") as f:
        return yaml.safe_load(f)

def get_region_by_name(name, sites=None):
    if sites is None:
        sites = load_test_sites()
    for site in sites["locations"]:
        if site["name"] == name:
            return site
    raise KeyError(f"Region not found: {name}")

def check_not_null(key):
    if key is None or all(l is None for l in key):
        return False
    else:
        return True

def get_bbox_shapely(lat, lon, buffer_deg) -> list:
    point = Point(lon, lat)
    # Creating a 'square' buffer
    bbox_poly = point.buffer(buffer_deg, cap_style=3) 
    return bbox_poly.bounds  # Returns (min_lon, min_lat, max_lon, max_lat)

In [8]:
site = get_region_by_name("cook_inlet_very_turbid_water")
#site = get_region_by_name("chesapeake_bay")
#site = get_region_by_name("rio_de_la_plata")



spatial = site["spatial_extent"]
if check_not_null(spatial["bbox"]):
    spatial_extent = spatial["bbox"]
elif check_not_null(spatial["latlon"]):
    spatial_extent = get_bbox_shapely(spatial["latlon"][0],
                                      spatial["latlon"][1],
                                      spatial["buffer"])
else:
    raise ValueError("Missing spatial extent")

if any([check_not_null(site["dates"]["start"]), check_not_null(site["dates"]["end"])]):
    
    temporal = [
        datetime.fromisoformat(site["dates"]["start"]),
        datetime.fromisoformat(site["dates"]["end"]),
    ]
else:
    raise ValueError("Missing temporal inputs")

## Calculate Kd from SlideRule

### Setting up configuration values

There are two ways to input configuration values:
1. from a `config.yaml` file
2. by manually entering them

For interactive coding, we recommend - and demonstrate below - a combination of these methods. This approach avoids the need to manually enter all inputs while providing flexibility to modify any inputs as desired.

:warning: Currently, the user MUST update the spatial and temporal extents included as defaults in the `config.yaml`, there or here.

In [9]:
# get configuration values from config.yaml
# supply `config_path='path\to\your\custom_config.yaml'` into `get_args()` if your file is not called `config.yaml`
kd_args = aok.main.get_args()

In [10]:
kd_args.spatial=spatial['bbox']

In [11]:
kd_args.temporal=[site["dates"]["start"], site["dates"]["end"]]

In [12]:
## Attempt to get the data using base...
from aok.core.datarequest import DataRequest

# Create a DataRequest object with spatial extent and temporal inputs
# TODO: add flags for other atl products
request = DataRequest(
    spatial=kd_args.spatial,
    date_range=kd_args.temporal,
    #(site["dates"]["start"], site["dates"]["end"]),
    output="geodataframe",
    beams= "all",
    download_dir="./test_data",
    need_atl03=True,
    need_atl24=False,  # Set to True if you want bathymetry data merged in
)

In [13]:
# Fetch data from SlideRule and get the geodataframe of photons
request.get_sliderule_data()

2026-07-16 14:28:37,270 - INFO - proxy request <AppServer.12444> querying resources for gebco

DataRequest(spatial=[-150.622053, 61.045382, -150.361757, 61.171146], date_range=['2025-08-21', '2025-08-22'], time_range=None, beams='all', output='geodataframe', download_dir='./test_data', need_atl03=True, need_atl24=False, need_gebco=True, need_shoreline=True, need_jpl_temperature=False, version_atl03=None, version_atl24=None, variables_atl03=None, variables_atl24=None, shoreline_data=None, land_ocean_mask=None, options={}, photons=                               segment_ph_cnt  ref_azimuth  gebco.fileid  \
time_ns
2025-08-22 14:13:06.441814784               5     1.358289           [0]
2025-08-22 14:13:06.442314752               5     1.358289           [0]
2025-08-22 14:13:06.442314752               5     1.358289           [0]
2025-08-22 14:13:06.442814720               5     1.358289           [0]
2025-08-22 14:13:06.442814720               5     1.358289           [0]
...                                       ...          ...           ...
2025-08-21 01:49:18.395253504             240     1.128917  [4294967296]
2025-08-21 01:49:18.395253504             240     1.128917  [4294967296]
2025-08-21 01:49:18.395253504             240     1.128917  [4294967296]
2025-08-21 01:49:18.395253504             240     1.128917  [4294967296]
2025-08-21 01:49:18.395253504             240     1.128917  [4294967296]

                               segment_dist_x  dist_ph_along  region  \
time_ns
2025-08-22 14:13:06.441814784    1.325918e+07      15.094666       5
2025-08-22 14:13:06.442314752    1.325918e+07      17.199505       5
2025-08-22 14:13:06.442314752    1.325918e+07      18.212816       5
2025-08-22 14:13:06.442814720    1.325918e+07      18.694416       5
2025-08-22 14:13:06.442814720    1.325918e+07      19.784868       5
...                                       ...            ...     ...
2025-08-21 01:49:18.395253504    6.817296e+06      19.385723       3
2025-08-21 01:49:18.395253504    6.817296e+06      19.386427       3
2025-08-21 01:49:18.395253504    6.817296e+06      19.386257       3
2025-08-21 01:49:18.395253504    6.817296e+06      19.386675       3
2025-08-21 01:49:18.395253504    6.817296e+06      18.927294       3

                               segment_length  gt  spacecraft_velocity  \
time_ns
2025-08-22 14:13:06.441814784       20.021160  50          7098.117676
2025-08-22 14:13:06.442314752       20.021160  50          7098.117676
2025-08-22 14:13:06.442314752       20.021160  50          7098.117676
2025-08-22 14:13:06.442814720       20.021160  50          7098.117676
2025-08-22 14:13:06.442814720       20.021160  50          7098.117676
...                                       ...  ..                  ...
2025-08-21 01:49:18.395253504       20.022305  40          7098.862793
2025-08-21 01:49:18.395253504       20.022305  40          7098.862793
2025-08-21 01:49:18.395253504       20.022305  40          7098.862793
2025-08-21 01:49:18.395253504       20.022305  40          7098.862793
2025-08-21 01:49:18.395253504       20.022305  40          7098.862793

                               solar_elevation  ... srcid  \
time_ns                                         ...
2025-08-22 14:13:06.441814784        -2.454211  ...     4
2025-08-22 14:13:06.442314752        -2.454211  ...     4
2025-08-22 14:13:06.442314752        -2.454211  ...     4
2025-08-22 14:13:06.442814720        -2.454211  ...     4
2025-08-22 14:13:06.442814720        -2.454211  ...     4
...                                        ...  ...   ...
2025-08-21 01:49:18.395253504        26.565836  ...    11
2025-08-21 01:49:18.395253504        26.565836  ...    11
2025-08-21 01:49:18.395253504        26.565836  ...    11
2025-08-21 01:49:18.395253504        26.565836  ...    11
2025-08-21 01:49:18.395253504        26.565836  ...    11

                                                 gebco.time_ns  cycle  \
time_ns
2025-08-22 14:13:06.441814784  [2024-07-02T00:00:00.000000000]     28
2025-08-22 14:13:06.442314752  [2024-07-02T00:00:00.000000000]     28
2025-08-22 14:13:06.442314752  [2024-07-02T00:00:00.000000000]     28
2025-08-22 14:13:06.442814720  [2024-07-02T00:00:00.000000000]     28
2025-08-22 14:13:06.442814720  [2024-07-02T00:00:00.000000000]     28
...                                                        ...    ...
2025-08-21 01:49:18.395253504  [2024-07-02T00:00:00.000000000]     28
2025-08-21 01:49:18.395253504  [2024-07-02T00:00:00.000000000]     28
2025-08-21 01:49:18.395253504  [2024-07-02T00:00:00.000000000]     28
2025-08-21 01:49:18.395253504  [2024-07-02T00:00:00.000000000]     28
2025-08-21 01:49:18.395253504  [2024-07-02T00:00:00.000000000]     28

                               photon_conf  reference_photon_lon  \
time_ns
2025-08-22 14:13:06.441814784            0           -150.361804
2025-08-22 14:13:06.442314752            0           -150.361804
2025-08-22 14:13:06.442314752            0           -150.361804
2025-08-22 14:13:06.442814720            0           -150.361804
2025-08-22 14:13:06.442814720            0           -150.361804
...                                    ...                   ...
2025-08-21 01:49:18.395253504            4           -150.503647
2025-08-21 01:49:18.395253504            4           -150.503647
2025-08-21 01:49:18.395253504            4           -150.503647
2025-08-21 01:49:18.395253504            4           -150.503647
2025-08-21 01:49:18.395253504            0           -150.503647

                               background_rate_sr  segment_id  ph_index_beg  \
time_ns
2025-08-22 14:13:06.441814784        23622.046875      661992       1713836
2025-08-22 14:13:06.442314752        23622.046875      661992       1713836
2025-08-22 14:13:06.442314752        23622.046875      661992       1713836
2025-08-22 14:13:06.442814720        23622.046875      661992       1713836
2025-08-22 14:13:06.442814720        23622.046875      661992       1713836
...                                           ...         ...           ...
2025-08-21 01:49:18.395253504       780746.937500      340059       6875061
2025-08-21 01:49:18.395253504       780746.937500      340059       6875061
2025-08-21 01:49:18.395253504       780746.937500      340059       6875061
2025-08-21 01:49:18.395253504       780746.937500      340059       6875061
2025-08-21 01:49:18.395253504       780746.937500      340059       6875061

                               quality_ph                     geometry
time_ns
2025-08-22 14:13:06.441814784           0   POINT (-150.3618 61.12668)
2025-08-22 14:13:06.442314752           0  POINT (-150.36173 61.12666)
2025-08-22 14:13:06.442314752           0  POINT (-150.36179 61.12666)
2025-08-22 14:13:06.442814720           0  POINT (-150.36162 61.12664)
2025-08-22 14:13:06.442814720           0  POINT (-150.36168 61.12664)
...                                   ...                          ...
2025-08-21 01:49:18.395253504           0  POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504           0  POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504           0  POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504           0  POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504           0  POINT (-150.50369 61.17107)

[137857 rows x 33 columns], metadata={'ATL03': {'request_type': 'atl03', 'n_rows': 137857, 'columns': ['segment_ph_cnt', 'ref_azimuth', 'gebco.fileid', 'segment_dist_x', 'dist_ph_along', 'region', 'segment_length', 'gt', 'spacecraft_velocity', 'solar_elevation', 'gebco.value', 'high_rate/backg_c', 'reference_photon_lat', 'delta_time', 'h_ph', 'rgt', 'ph_index', 'photon_height', 'background_rate', 'ref_elev', 'beam_id', 'relative_AT_dist', 'y_atc', 'srcid', 'gebco.time_ns', 'cycle', 'photon_conf', 'reference_photon_lon', 'background_rate_sr', 'segment_id', 'ph_index_beg', 'quality_ph', 'geometry']}}, sources=['sliderule'], products=['ATL03'])

In [14]:
params = request.build_atl03_params()

In [15]:
request_atl03 = sliderule.run("atl03x", params)

2026-07-16 14:28:40,507 - INFO - proxy request <AppServer.12446> querying resources for gebco

In [16]:
request.photons.columns

Index(['segment_ph_cnt', 'ref_azimuth', 'gebco.fileid', 'segment_dist_x',
       'dist_ph_along', 'region', 'segment_length', 'gt',
       'spacecraft_velocity', 'solar_elevation', 'gebco.value',
       'high_rate/backg_c', 'reference_photon_lat', 'delta_time', 'h_ph',
       'rgt', 'ph_index', 'photon_height', 'background_rate', 'ref_elev',
       'beam_id', 'relative_AT_dist', 'y_atc', 'srcid', 'gebco.time_ns',
       'cycle', 'photon_conf', 'reference_photon_lon', 'background_rate_sr',
       'segment_id', 'ph_index_beg', 'quality_ph', 'geometry'],
      dtype='object')

In [17]:
request.photons

,segment_ph_cnt,ref_azimuth,gebco.fileid,segment_dist_x,dist_ph_along,region,segment_length,gt,spacecraft_velocity,solar_elevation,...,srcid,gebco.time_ns,cycle,photon_conf,reference_photon_lon,background_rate_sr,segment_id,ph_index_beg,quality_ph,geometry
time_ns,,,,,,,,,,,,,,,,,,,,,
2025-08-22 14:13:06.441814784,5,1.358289,[0],1.325918e+07,15.094666,5,20.021160,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.3618 61.12668)
2025-08-22 14:13:06.442314752,5,1.358289,[0],1.325918e+07,17.199505,5,20.021160,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36173 61.12666)
2025-08-22 14:13:06.442314752,5,1.358289,[0],1.325918e+07,18.212816,5,20.021160,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36179 61.12666)
2025-08-22 14:13:06.442814720,5,1.358289,[0],1.325918e+07,18.694416,5,20.021160,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36162 61.12664)
2025-08-22 14:13:06.442814720,5,1.358289,[0],1.325918e+07,19.784868,5,20.021160,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36168 61.12664)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-08-21 01:49:18.395253504,240,1.128917,[4294967296],6.817296e+06,19.385723,3,20.022305,40,7098.862793,26.565836,...,11,[2024-07-02T00:00:00.000000000],28,4,-150.503647,780746.937500,340059,6875061,0,POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504,240,1.128917,[4294967296],6.817296e+06,19.386427,3,20.022305,40,7098.862793,26.565836,...,11,[2024-07-02T00:00:00.000000000],28,4,-150.503647,780746.937500,340059,6875061,0,POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504,240,1.128917,[4294967296],6.817296e+06,19.386257,3,20.022305,40,7098.862793,26.565836,...,11,[2024-07-02T00:00:00.000000000],28,4,-150.503647,780746.937500,340059,6875061,0,POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504,240,1.128917,[4294967296],6.817296e+06,19.386675,3,20.022305,40,7098.862793,26.565836,...,11,[2024-07-02T00:00:00.000000000],28,4,-150.503647,780746.937500,340059,6875061,0,POINT (-150.50366 61.17108)
2025-08-21 01:49:18.395253504,240,1.128917,[4294967296],6.817296e+06,18.927294,3,20.022305,40,7098.862793,26.565836,...,11,[2024-07-02T00:00:00.000000000],28,0,-150.503647,780746.937500,340059,6875061,0,POINT (-150.50369 61.17107)

In [18]:
type(request.photons)

geopandas.geodataframe.GeoDataFrame

In [19]:
sr_photons = request.photons

In [20]:
# Display the result
print(f"Retrieved {len(sr_photons)} photons from SlideRule")
sr_photons.head()

Retrieved 137857 photons from SlideRule

,segment_ph_cnt,ref_azimuth,gebco.fileid,segment_dist_x,dist_ph_along,region,segment_length,gt,spacecraft_velocity,solar_elevation,...,srcid,gebco.time_ns,cycle,photon_conf,reference_photon_lon,background_rate_sr,segment_id,ph_index_beg,quality_ph,geometry
time_ns,,,,,,,,,,,,,,,,,,,,,
2025-08-22 14:13:06.441814784,5,1.358289,[0],1.325918e+07,15.094666,5,20.02116,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.3618 61.12668)
2025-08-22 14:13:06.442314752,5,1.358289,[0],1.325918e+07,17.199505,5,20.02116,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36173 61.12666)
2025-08-22 14:13:06.442314752,5,1.358289,[0],1.325918e+07,18.212816,5,20.02116,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36179 61.12666)
2025-08-22 14:13:06.442814720,5,1.358289,[0],1.325918e+07,18.694416,5,20.02116,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36162 61.12664)
2025-08-22 14:13:06.442814720,5,1.358289,[0],1.325918e+07,19.784868,5,20.02116,50,7098.117676,-2.454211,...,4,[2024-07-02T00:00:00.000000000],28,0,-150.361804,23622.046875,661992,1713836,0,POINT (-150.36168 61.12664)

Expected Tracks: 1214, 1215
Expected Cycles: 06

## Compare Outputs

In [22]:
aok.main.run_pipeline(kd_args)

2026-07-16 14:43:17,092 - INFO - proxy request <AppServer.13883> querying resources for gebco
2026-07-16 14:43:17,093 - INFO - request <AppServer.13883> retrieved 2 resources
2026-07-16 14:43:17,094 - INFO - Starting proxy for atl03x to process 2 resource(s) with 2 thread(s)
2026-07-16 14:43:17,094 - INFO - Attempt 1 of 3 ATL09 CMR request: {"name_filter":"*_103628??_*","asset":"icesat2-atl09"}
2026-07-16 14:43:17,095 - INFO - Attempt 1 of 3 ATL09 CMR request: {"asset":"icesat2-atl09","name_filter":"*_101328??_*"}
2026-07-16 14:43:19,550 - INFO - Processing atmospheric data from ATL09_20250821013321_10132801_007_01.h5
2026-07-16 14:43:19,550 - INFO - Processing atmospheric data from ATL09_20250822134200_10362801_007_01.h5
2026-07-16 14:43:20,150 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt1r] with 0 rows and 16 columns
2026-07-16 14:43:21,439 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt3r] with 3917 rows and 29 columns
2026-07-16 14:43:21,440 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt2r] with 0 rows and 16 columns
2026-07-16 14:43:21,440 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt1l] with 0 rows and 16 columns
2026-07-16 14:43:21,441 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt2l] with 0 rows and 16 columns
2026-07-16 14:43:21,441 - INFO - request <AppServer.13496> on ATL03_20250822140806_10362805_007_01.h5 generated dataframe [gt3l] with 5 rows and 29 columns
2026-07-16 14:43:21,442 - INFO - Successfully completed processing resource [2 out of 2]: ATL03_20250822140806_10362805_007_01.h5
2026-07-16 14:43:22,198 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt1l] with 13180 rows and 29 columns
2026-07-16 14:43:22,199 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt2l] with 18052 rows and 29 columns
2026-07-16 14:43:22,199 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt3l] with 10658 rows and 29 columns
2026-07-16 14:43:22,200 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt2r] with 41773 rows and 29 columns
2026-07-16 14:43:22,200 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt3r] with 24191 rows and 29 columns
2026-07-16 14:43:22,201 - INFO - request <AppServer.14431> on ATL03_20250821014853_10132803_007_01.h5 generated dataframe [gt1r] with 26081 rows and 29 columns
2026-07-16 14:43:22,201 - INFO - Successfully completed processing resource [1 out of 2]: ATL03_20250821014853_10132803_007_01.h5
2026-07-16 14:43:22,546 - INFO - Writing output file: /home/jovyan/Desktop/aok/doc/source/example_notebooks/test_data/atl03_output.parquet
2026-07-16 14:43:22,756 - INFO - Closing output file: /home/jovyan/Desktop/aok/doc/source/example_notebooks/test_data/atl03_output.parquet
2026-07-16 14:43:23,197 - INFO - request <AppServer.13890> retrieved 0 resources
2026-07-16 14:43:23,198 - CRITICAL - Alert <-1>: request <AppServer.13890> has no resources to process
2026-07-16 14:43:23,416 - WARNING - Solar background filter is DISABLED via --disable_solar_background_filter but this granule is a daytime pass (max solar elevation = 26.6°, daytime threshold = 6.0°). This filter is recommended for daytime passes.
2026-07-16 14:43:23,587 - INFO - Solar background filter (multiplier=1.5) removed 0 photons (from 95962 to 95962).

Processing binning for beam: 1

KeyError: 'lat'

In [ ]:
#kd_df = pd.read_csv("./results/2023-07-04_subsurface_photons.csv")
kd_df = pd.read_csv("./results/2025-08-21_subsurface_photons.csv")

In [ ]:
kd_df.columns

dictionary location:
orbit_info/sc orient : direction of spacecraft; backward (0), forward (1), transition (2)
ancillary_data/atlas_engineering/transmit/tx_pulse_energy mean, sd, min, max of transmit energy; strong transmit energy = strong beam and vice versa.

spot - odds are strong, evens are weak; independent of spacecraft orientation